# Install percona MySQL server from Ansible Galaxy
 - src: Xobb.percona
# Install PHP for RedHat/CentOS/Debian/Ubuntu from Ansible Galaxy
 - src: geerlingguy.php
#   version: 2.0.3
# Install PHP XDebug for Linux from Ansible Galaxy
 - src: geerlingguy.php-xdebug
#   version: 2.1.0
# Install Nginx for Linux/UNIX from Ansible Galaxy
 - src: geerlingguy.nginx
# Install Memcached for Linux from Ansible Galaxy
# - src: geerlingguy.memcached
#   version: 1.0.4
# Install Redis from Ansible Galaxy
 - src: geerlingguy.redis
#   version: 1.2.0
# Install general role from github
 - src: fradee.general
# Install magentotols role from github
 - src: fradee.magentotools
# Install Java for Linux from Ansible Galaxy
# - src: geerlingguy.java